services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./resources/migrations:/docker-entrypoint-initdb.d/

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,lambda
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"