services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://testuser:testpassword@db:5432/testdb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - postgres
      - localstack
    command: "pytest --asyncio-mode=strict --junitxml=/usr/src/app/test-results/results.xml"